version: "3.8"
services:
  client:
    build: ./client
    container_name: client_container
    ports:
      - "3000:3000"
  server:
    build: ./server
    container_name: server_container
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
